EWSweb/Contact/urls.py
from django.urls import path
from . import views
app_name = 'Contact'

urlpatterns = [
    path('', views.Contact, name = 'Contact'),
    path('getContact/', views.getContact, name="getContact"),
]

EWSweb/EWSweb/urls.py
"""EWSweb URL Configuration

Các Apps trong Website:
    1. Home: Trang chủ
    2. EarlyWarningNote: Thông tin cảnh báo
    3. MonitoringData: Dữ liệu quan trắc
    4. TraningMaterial: Tài liệu hướng dẫn - tập huấn
    5. Contact: Thông tin liên hệ và quản lý account

Danh sách `urlpatterns` định tuyến URL đến các chế độ xem. Để biết thêm thông tin vui lòng xem:
     https://docs.djangoproject.com/en/4.0/topics/http/urls/
Ví dụ:
Chế độ xem chức năng
     1. Thêm nhập: từ chế độ xem nhập của my_app
     2. Thêm URL vào urlpatterns: path ('', views.home, name = 'home')
Chế độ xem dựa trên lớp
     1. Thêm nhập: from other_app.views import Trang chủ
     2. Thêm URL vào urlpatterns: path ('', Home.as_view (), name = 'home')
Bao gồm một URLconf khác
     1. Nhập hàm include (): từ django.urls nhập bao gồm, đường dẫn
     2. Thêm một URL vào urlpatterns: path ('blog /', include ('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from employees import views as employees
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from import_excel_db import views
from editors.views import EditorChartView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    #     path('department/<int:id>/', employees.get_employees)
    path('EarlyWarningNote', include('EarlyWarningNote.urls')),
    path('MonitoringData', include('MonitoringData.urls')),
    path('TrainingMaterial', include('TrainingMaterial.urls')),
    path('Contact', include('Contact.urls')),
    path('Register', include('Register.urls')),
    path('Upload', include('Upload.urls')),
    path('import_excel_db', views.simple_upload),
    path('Login', include('Login.urls')),
    path('editors', EditorChartView.as_view(), name='index')
] + staticfiles_urlpatterns()
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "QUAN TRẮC CẢNH BÁO THIÊN TAI"

EWSweb/EarlyWarningNote/urls.py
from django.urls import path
from . import views
app_name = 'EarlyWarningNote'
urlpatterns = [
    path('', views.EarlyWarningNote, name = 'EarlyWarningNote'),
]

EWSweb/Home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'Home'
urlpatterns = [
    path('', views.index, name="Home"),
    path('<int:id>/', views.postDetail, name='postDetail'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view, {'next_page': '/'}, name='logout')

]

EWSweb/MonitoringData/urls.py
from django.urls import path
from . import views
app_name = 'MonitoringData'
urlpatterns = [
    path('', views.MonitoringData, name = 'MonitoringData'),
]

EWSweb/Register/urls.py
from django.urls import path
from . import views
app_name = 'Register'

# Create your views here
urlpatterns = [
    path('', views.Register, name = 'Register'),
    path('getRegister/', views.getRegister, name = 'getRegister'),
]

EWSweb/TrainingMaterial/urls.py
from django.urls import path
from . import views
app_name = 'TrainingMaterial'
urlpatterns = [
    path('', views.TrainingMaterial, name = 'TrainingMaterial'),
]

EWSweb/Upload/urls.py
from django.urls import path
from .import views
app_name = 'Upload'

urlpatterns = [
    path('', views.index.as_view(), name = 'Upload'),
    
]

EWSweb/Home/models.py
from django.db import models

# Create your models here.


class department(models.Model):
    department_id = models.AutoField(primary_key=True)
    name = models.CharField(max_length=100, null=False)

    def __str__(self):
        return f"{self.department_id},{self.name}"

# class post(models.Model):
#     post_id= models.AutoField(primary_key=True)
#     title = models.CharField(max_length=255,null=False)
#     content=models.TextField(null=False)
#     img = models.ImageField(upload_to= 'images',null=True, default=None)
# def __str__(self):
#         return f"{self.post_id},{self.title},{self.content},{self.img}"


class postForm(models.Model):
    title = models.CharField(max_length=255)
    body = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title


class Sites(models.Model):
    Province = models.CharField(max_length=50)
    Distric = models.CharField(max_length=50)
    Commune = models.CharField(max_length=50)
    Risk3h = models.CharField(max_length=50)
    Risk12h = models.CharField(max_length=50)
    Risk24h = models. CharField(max_length=50)
    Risk48h = models.CharField(max_length=50)

EWSweb/Register/models.py
from django.db import models

# Create your models here.
class Registermodel(models.Model):
	username = models.CharField(max_length = 25)
	email = models.EmailField()
	company = models.CharField(max_length = 25)
	phonenumber = models.CharField(max_length = 11)
	password = models.CharField(max_length = 13)
	address = models.CharField(max_length = 50)

	def __str__(self):
		return self.username

EWSweb/Upload/models.py
from django.db import models

# Create your models here.


class formUpload(models.Model):
    local = models.CharField(max_length=25)
    hazard = models.CharField(max_length=11)
    discribe = models.CharField(max_length=30)
    image = models.FileField(upload_to='Media/')

    def __str__(self):
        return self.local, self.image

EWSweb/import_excel_db/models.py
from django.db import models

# Create your models here.


class Sites(models.Model):
    Province = models.CharField(max_length=50)
    Distric = models.CharField(max_length=50)
    Commune = models.CharField(max_length=50)
    Risk3h = models.CharField(max_length=50)
    Risk12h = models.CharField(max_length=50)
    Risk24h = models. CharField(max_length=50)
    Risk48h = models.CharField(max_length=50)

EWSweb/Home/forms.py
from django import forms
from .models import Sites
import re
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist


class SiteData(forms.Form):
    class meta:
        model = Sites
        fields = '__all__'


class RegistrationForm(forms.Form):
    username = forms.CharField(label='Tài khoản', max_length=30)
    email = forms.EmailField(label='Email')
    password1 = forms .CharField(
        label='Mật khẩu', widget=forms.PasswordInput())
    password2 = forms .CharField(
        label='Nhập lại mật khẩu', widget=forms.PasswordInput())

    def clean_password2(self):
        if 'password1' in self.cleaned_data:
            password1 = self.cleaned_data['password1']
            password2 = self.cleaned_data['password2']
            if password1 == password2 and password1:
                return password2
            raise forms.ValidationError("Mật khẩu không hợp lê")

    def clean_username(self):
        username = self.cleaned_data['username']
        # if not re.search(r'^\W+$', username):
        #     raise forms.ValidationError("Tên tài khoản chứa kí tự đặc biệt")
        try:
            User.objects.get(username=username)
        except ObjectDoesNotExist:
            return username
        raise forms.ValidationError("Tài khoản đã tồn tại")

    def save(self):
        User.objects.create_user(
            username=self.cleaned_data['username'], email=self.cleaned_data['email'], password=self.cleaned_data['password1'])

EWSweb/Register/forms.py
from django import forms
from .models import Registermodel

class Registerform(forms.ModelForm):
	class Meta:
		model = Registermodel
		fields = ['username', 'email', 'company', 'phonenumber', 'password', 'address']

EWSweb/Upload/forms.py
from django import forms

class UploadMulti(forms.Form):
	local = forms.CharField(max_length = 25)
	hazard = forms.CharField(max_length = 11)
	discribe = forms.CharField(max_length = 30)
	image = forms.FileField(widget=forms.ClearableFileInput(attrs={'multiple': True}))
	

 

EWSweb/Home/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import postForm
import pandas as pd
from .models import Sites
from .resources import SitesResources
from django.contrib import messages
from tablib import Dataset
from .models import Sites as Sites_model
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect
from .forms import RegistrationForm
from django.contrib.auth.models import User


# Create your Home views here.
# def get_home(request):
#     post_list = post_model.objects.filter().order_by('post_id')
#     return render(request, 'index.html', {'post_list': post_list})


# def index(request):
#     pF = postForm.objects.all()
#     return render(request, 'Home/index.html', {'pF': pF})


def postDetail(request, id):
    pD = postForm.objects.get(id=id)
    return render(request, 'Home/postDetail.html', {'pD': pD})


def export(request):
    site_resource = SitesResources()
    dataset = site_resource.export()
    response = HttpResponse(
        dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="sites.xls"'
    return response


def index(request):
    sM = Sites_model.objects.filter()
    pF = postForm.objects.all().order_by("-created_at")
    return render(request, 'Home/index.html', {'sM': sM, 'pF': pF})


def simple_upload(request):

    if request.method == 'POST':
        site_resource = SitesResources()
        dataset = Dataset()
        new_site = request.FILES['myfile']

        imported_data = dataset.load(new_site.read(), format='xlsx')
        # print(imported_data)
        for data in imported_data:
            value = Sites(
                data[0],
                data[1],
                data[2],
                data[3],
                data[4],
                data[5],
                data[6],
                data[7],
            )
        value.save()
    return render(request, 'upload.html')


def register(request):
    form = RegistrationForm()
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect('/')
    return render(request, 'Home/register.html', {'form': form})

EWSweb/Register/views.py
from django.shortcuts import render
# from django.views import View
from django.http import HttpResponse
# from django.http import HttpResponseRedirect
from .forms import Registerform
# from .models import Registermodel
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login


# Create your views here.
def Register(request):
    context = {'RF': Registerform}
    return render(request, 'Register/Register.html', context)


def getRegister(request):
    if request.method == "POST":
        RF = Registerform(request.POST)
        if RF.is_valid():
            saveRF = User.objects.create(
                username=RF.cleaned_data['username'],
                email=RF.cleaned_data['email'],
                password=RF.cleaned_data['password'])
            saveRF.set_password(RF.cleaned_data['password'])
            saveRF.save()
            return HttpResponse('Đăng kí thành công')
        else:
            return HttpResponse('Đăng kí không thành công')

EWSweb/Upload/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .forms import UploadMulti
from .models import formUpload
from django.views.generic.edit import FormView

class index(FormView):
	def get (self, request):
		form = UploadMulti
		return render(request, 'Upload/Upload.html', {'form': form})
	def post(self, request):
		form_class = UploadMulti
		form = self.get_form(form_class)
		files = request.FILES.getlist('image')
		if form.is_valid():
			for f in files:
				instance = formUpload(image=f)
				instance.save()
		return HttpResponse('Bạn đã gửi thông tin cảnh báo thành công, thông tin này sẽ được cán bộ xử lý ngay lập tức!')

EWSweb/import_excel_db/views.py
from django.shortcuts import render
from .models import Sites
from .resources import SitesResources
from django.contrib import messages
from tablib import Dataset
from django.http import HttpResponse

# Create your views here.


def export(request):
    site_resource = SitesResources()
    dataset = site_resource.export()
    response = HttpResponse(
        dataset.xls, content_type='application/vnd.ms-excel')
    response['Content-Disposition'] = 'attachment; filename="sites.xls"'
    return response


def simple_upload(request):
    if request.method == 'POST':
        site_resource = SitesResources()
        dataset = Dataset()
        new_site = request.FILES['myfile']

        imported_data = dataset.load(new_site.read(), format='xlsx')
        # print(imported_data)
        for data in imported_data:
            value = Sites(
                data[0],
                data[1],
                data[2],
                data[3],
                data[4],
                data[5],
                data[6],
                data[7],
            )
        value.save()
    return render(request, 'upload.html')

EWSweb/Home/templates/Home/base.html
<!DOCTYPE html>
<html>
<head>
	{% load static %}
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta property = "og:image" content="https://quantrac.maiatech.com.vn/Home/static/images/logo.png">
	<title>Cảnh báo nguy cơ trượt lở - lũ bùn đá - lũ quét</title>
	<link href="Home/static/images/Logo_web.jpg" rel="shortcut icon">
	{% comment %} <link rel="stylesheet" href="http://truotlo.com/libs/bootstrap/css/bootstrap.min.css" type="text/css"> {% endcomment %}
	{% comment %} <link rel="stylesheet" href="{%static 'css/style.css'%}" type="text/css"> {% endcomment %}
	<link rel="stylesheet" href="Home/static/css/styles.css">
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
	<script src="https://code.highcharts.com/highcharts.js"></script>
	<script src="https://code.highcharts.com/modules/windbarb.js"></script>
	<script src="https://code.highcharts.com/modules/datagrouping.js"></script>
	<script src="https://code.highcharts.com/modules/exporting.js"></script>
	<script src="https://code.highcharts.com/modules/export-data.js"></script>
	<script src="https://code.highcharts.com/modules/accessibility.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/js/bootstrap.bundle.min.js"></script>
	<!--Chart js-->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.js" integrity="sha256-Uv9BNBucvCPipKQ2NS9wYpJmi8DTOEfTA/nH2aoJALw=" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.8.0/Chart.min.css" integrity="sha256-aa0xaJgmK/X74WM224KMQeNQC2xYKwlAt08oZqjeF0E=" crossorigin="anonymous" />
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>

    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css"
      rel="stylesheet"
    />
    <link
      href="https://getbootstrap.com/docs/5.3/assets/css/docs.css"
      rel="stylesheet"
    />
	
</head>
		<div class=" text-center bg-image rounded-3 object-fit-contain" style="
		background-image: url('Home/static/images/Photo 1.jpg'); background-repeat: no-repeat; background-size: cover;background-position: center;
		height: 450px;
	  ">
	  <div class="mask h-100" style="background-color: rgba(0, 0, 0, 0.5);">
		<div class=" container h-100 position-relative">
		   <nav class="navbar navbar-expand-lg navbar-light">
		  <div class="container ">
			 <a class="navbar-brand text-white" href="#">
			  <img src="Home/static/images/logo.png" class="logo" alt="">
			</a>
			<div class="d-flex justify-content-">
				 <button
			  class="btn btn-danger navbar-toggler border-3 px-2"
			  type="button"
			  data-bs-toggle="offcanvas"
			  data-bs-target="#offcanvasExample"
			  aria-controls="offcanvasExample"
			>
			  <span class="navbar-toggler-icon"></span>
			</button>
			<div
			  class="offcanvas offcanvas-start-lg bg-white"
			  tabindex="-1"
			  id="offcanvasExample"
			  aria-labelledby="offcanvasExampleLabel"
			>
			  <div class="offcanvas-header d-flex d-lg-none bg-light">
				<h5 class="offcanvas-title text-black" id="offcanvasExampleLabel">
				  Navbar
				</h5>
				<a
				  href="javascript:void(0) "
				  class="text-reset p-0"
				  data-bs-dismiss="offcanvas"
				  aria-label="close"
				>
				  <svg
					xmlns="http://www.w3.org/2000/svg"
					width="24"
					height="24"
					fill="#000"
					class="bi bi-x-circle"
					viewBox="0 0 16 16"
				  >
					<path
					  d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"
					/>
					<path
					  d="M4.646 4.646a.5.5 0 0 1 .708 0L8 7.293l2.646-2.647a.5.5 0 0 1 .708.708L8.707 8l2.647 2.646a.5.5 0 0 1-.708.708L8 8.707l-2.646 2.647a.5.5 0 0 1-.708-.708L7.293 8 4.646 5.354a.5.5 0 0 1 0-.708z"
					/>
				  </svg>
				</a>
			  </div>
			  <div class="offcanvas-body p-lg-0 ">
				<ul class="navbar-nav">
					<li class="nav-item">
						<a href="{% url 'Home:Home' %}" aria-current="page" class="nav-link nav-link activ">Trang chủ</a>
					 
					</li>
					<li class="nav-item">
						<a href="{% url 'EarlyWarningNote:EarlyWarningNote' %}" aria-current="page" class="nav-link w-nav-link">Cảnh báo sớm</a>
	
					</li>
					<li class="nav-item">
						<a href="{% url 'MonitoringData:MonitoringData' %}" aria-current="page" class="nav-link w-nav-link">Quan trắc</a>
	
					</li>
					<li class="nav-item">
						<a href="{% url 'TrainingMaterial:TrainingMaterial' %}" aria-current="page" class="nav-link w-nav-link">Tài liệu tập huấn</a>
					</li>
					<li class="nav-item">
					  <a href="{% url 'Contact:Contact' %}" aria-current="page" class="nav-link w-nav-link">Liên hệ</a>
					</li>
					
				</ul>
			  </div>
			</div>
			</div>
		   
		 
		  </div>
		</nav>
		  <div class=" d-flex pt-3 justify-content-between align-items-center">
		   
			<a class="weather-logo text-decoration-none align-center text-center d-flex gap-3 justify-content-between text-white" href="https://www.msn.com/vi-vn/weather/forecast/in-Th%E1%BB%A5y-Khu%C3%AA,H%C3%A0-N%E1%BB%99i?loc=eyJsIjoiVGjhu6V5IEtodcOqIiwiciI6IkjDoCBO4buZaSIsImMiOiJWaeG7h3QgTmFtIiwiaSI6IlZOIiwiZyI6InZpLXZuIiwieCI6MTA1LjgxOTk5OTY5NDgyNDIyLCJ5IjoyMS4wNDM1MDA5MDAyNjg1NTV9&amp;weadegreetype=C" data-t="{&quot;n&quot;:&quot;weather_link&quot;,&quot;b&quot;:1,&quot;d&quot;:&quot;https://www.msn.com/vi-vn/weather/forecast/in-Th%E1%BB%A5y-Khu%C3%AA,H%C3%A0-N%E1%BB%99i?loc=eyJsIjoiVGjhu6V5IEtodcOqIiwiciI6IkjDoCBO4buZaSIsImMiOiJWaeG7h3QgTmFtIiwiaSI6IlZOIiwiZyI6InZpLXZuIiwieCI6MTA1LjgxOTk5OTY5NDgyNDIyLCJ5IjoyMS4wNDM1MDA5MDAyNjg1NTV9&amp;weadegreetype=C&quot;,&quot;c.t&quot;:36,&quot;c.v&quot;:&quot;weather&quot;,&quot;c.c&quot;:&quot;today&quot;,&quot;c.hl&quot;:&quot;28°C&quot;}" rel="noopener" target="_blank" aria-label="" title=""  style="display: flex;" aria-expanded="false">
				<div class="d-flex gap-1">
				  <span id="i_location" class="location-left dark-font-color weather text-white" title="" >Hà Nội,</span>
						<span id="current-time" class="weather text-white"></span>
				</div>
				<div class="thoitiet d-flex gap-1">
					<div class="weather-glyph-location text-wrapper-image-hidden weather">
						<img class="icon-svg" src="https://assets.msn.com/weathermapdata/1/static/svg/72/v2/card/CloudyV3.svg" alt="Có mây" class="">
					</div>
					<div class="weather loading">
					  <div class="temp"></div> 
					</div>
				</div> 
					
				 </a>
		   <div class="d-flex text-white align-items-center gap-1">
			{% if user.username %}
				<p>Accout:{{user.username}}</p>
			{% endif %}
			</div>
		</div> 
		  
		</div>
	  </div>
	
			
			</div>
	<div class="content">
		{%block scripts%}
		
	    {%endblock scripts%}


		{% block content %}

		{% endblock %}
	</div> 
	
	<script src="Home/static/js/MonitoringChart.js"></script>
	<script src="Home/static/js/EarlyWarningNoteChart.js"></script>
  </body>
 

  <script>
	var curDate = new Date();					      
	// Ngày hiện tại
	var curDay = curDate.getDate();					 
	// Tháng hiện tại
	var curMonth = curDate.getMonth() + 1;					      
	// Năm hiện tại
	var curYear = curDate.getFullYear();					 
	// Gán vào thẻ HTML
	document.getElementById('current-time').innerHTML =" " +  curDay + "/" + curMonth + "/" + curYear;
	//Nhiệt độ
	let weather = {
		apiKey: "062d92a2646152d39eb7845a608226cb",   // Nhập key lấy từ openweathermap.org
		fetchWeather: function (city) {
		  fetch(
			"https://api.openweathermap.org/data/2.5/weather?q=" +
			  city +
			  "&lang=vi&units=metric&appid=" +
			  this.apiKey
		  )
			.then((response) => {
			  if (!response.ok) {
				throw new Error("Không có địa điểm");
			  }
			  return response.json();
			})
			.then((data) => this.displayWeather(data));
		},
		displayWeather: function (data) {
		  const { temp, humidity } = data.main;
		  document.querySelector(".temp").innerText = temp + "°C";
		},
	  };
	  weather.fetchWeather("ha noi");
	</script>

	
</html>

EWSweb/Home/templates/Home/import_excel_db.html
{% block content %}
  <form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
 
    <div class="row">
        <div class="col-md-6 col-xs-12">
          <div class="x_panel">
            <div class="x_title">
              <h2>Import Excel Data into Database</h2>           
              <div class="clearfix"></div>
            </div>
            <div class="x_content">
              <div class="col-md-8 col-sm-12 col-xs-12 form-group">      
              </div>
                    <input type="file" name="myfile" class="form-control">
                             <button type="submit" class="btn btn-success" >Upload data using Pandas</button> 
                             <button type="submit" class="btn btn-success" >Upload data using Import_Export_Lib</button>   
                            </div>
                        </div>
                    </div>
                </div>
  </form>   
{% endblock %}

EWSweb/Home/templates/Home/postDetail.html
<!DOCTYPE html>
<html>
<head>
    {% extends 'Home/base.html' %}
</head>
{%block content%}
<body>
            
    {{pD.title}}
    {{pD.body}}
        
</body>
{% endblock%}
</html>

EWSweb/Home/templates/Home/register.html
<!DOCTYPE html>
<html>
<head>
	<title>Đăng kí thành viên mới</title>
<head>

{% extends 'Home/base.html' %}

<body>
{% block content %}
 
<div class="from form-group text-center container">
    <div class="section-heading">
        <h2 class="section-title">Đăng kí</h2>
        <div class="med-divider"></div>
    </div>
    <form action='.' method='POST' id="form1">
        {% csrf_token %}
        {{form.as_p}}
        <input type="submit" value="Đăng kí"/>
    </form>
</div>

{% endblock %}
</body>
</html>

EWSweb/Home/templates/Home/upload.html
<!DOCTYPE html>
<html>
<head>
    <title>Liên hệ, cung cấp thông tin cảnh báo</title>
<head>
  
  {% extends 'Home/base.html' %}
  
<body>
  {% block content %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <input type="file" name="myfile">
    <button type="submit">Upload</button>
  </form>
  
  {% endblock %}
</body>
</html>