EWSweb/Contact/urls.py
from django.urls import path
from . import views
app_name = 'Contact'

urlpatterns = [
    path('', views.Contact, name = 'Contact'),
    path('getContact/', views.getContact, name="getContact"),
]

EWSweb/EWSweb/urls.py
"""EWSweb URL Configuration

Các Apps trong Website:
    1. Home: Trang chủ
    2. EarlyWarningNote: Thông tin cảnh báo
    3. MonitoringData: Dữ liệu quan trắc
    4. TraningMaterial: Tài liệu hướng dẫn - tập huấn
    5. Contact: Thông tin liên hệ và quản lý account

Danh sách `urlpatterns` định tuyến URL đến các chế độ xem. Để biết thêm thông tin vui lòng xem:
     https://docs.djangoproject.com/en/4.0/topics/http/urls/
Ví dụ:
Chế độ xem chức năng
     1. Thêm nhập: từ chế độ xem nhập của my_app
     2. Thêm URL vào urlpatterns: path ('', views.home, name = 'home')
Chế độ xem dựa trên lớp
     1. Thêm nhập: from other_app.views import Trang chủ
     2. Thêm URL vào urlpatterns: path ('', Home.as_view (), name = 'home')
Bao gồm một URLconf khác
     1. Nhập hàm include (): từ django.urls nhập bao gồm, đường dẫn
     2. Thêm một URL vào urlpatterns: path ('blog /', include ('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include
from employees import views as employees
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

from import_excel_db import views
from editors.views import EditorChartView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Home.urls')),
    #     path('department/<int:id>/', employees.get_employees)
    path('EarlyWarningNote', include('EarlyWarningNote.urls')),
    path('MonitoringData', include('MonitoringData.urls')),
    path('TrainingMaterial', include('TrainingMaterial.urls')),
    path('Contact', include('Contact.urls')),
    path('Register', include('Register.urls')),
    path('Upload', include('Upload.urls')),
    path('import_excel_db', views.simple_upload),
    path('Login', include('Login.urls')),
    path('editors', EditorChartView.as_view(), name='index')
] + staticfiles_urlpatterns()
# if settings.DEBUG:
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

admin.site.site_header = "QUAN TRẮC CẢNH BÁO THIÊN TAI"

EWSweb/Home/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import LogoutView

app_name = 'Home'
urlpatterns = [
    path('', views.index, name="Home"),
    path('<int:id>/', views.postDetail, name='postDetail'),
    path('register/', views.register, name='register'),
    path('logout/', LogoutView.as_view, {'next_page': '/'}, name='logout')

]

EWSweb/Contact/models.py
from django.db import models


class contactForm(models.Model):
    username = models.CharField(max_length=100)
    email = models.EmailField()
    phone = models.CharField(max_length=10, null=True)
    body = models.TextField()
    # avatar = models.ImageField(upload_to='images',null=False, default=None)

    def __str__(self):
        return self.username

EWSweb/Contact/forms.py
from django import forms
from .models import contactForm


class contactForm(forms.ModelForm):
    class Meta:
        model = contactForm
        fields = ['username', 'phone', 'email', 'body']
# 	username = forms.CharField(max_length=100)
# email= forms.EmailField()

EWSweb/Contact/views.py
from django.shortcuts import render
from django.http import HttpResponse

# from django.views import View
# from django.contrib.auth.models import User
# from django.contrib.auth import authenticate, login
from .forms import contactForm

# class Contact(View):
# 	def get(sefl, request):
# 		LF = loginForm
# 		return render(request, 'Contact/Contact.html', {'LF': LF})
# 	def post(seft, request):
# 		username = request.POST['username']
# 		password = request.POST['password']
# 		user = authenticate(request, username=username, password=password)
# 		if user is not None:
# 			login(request, user)
# 			return render(request, 'Contact/Sendalarm.html')
# 		else:
# 			return HttpResponse('Đăng nhập không thành công')


def Contact(request):
    context = {'cf': contactForm}
    return render(request, 'Contact/Contact.html', context)


def getContact(request):
    if request.method == "POST":
        cf = contactForm(request.POST)
        if cf.is_valid():
            cf.save()
            return HttpResponse('save success')
    else:
        return HttpResponse('not POST')

EWSweb/Contact/templates/Contact/Contact.html
<!DOCTYPE html>
<html>
<head>
	<title>Liên hệ, cung cấp thông tin cảnh báo</title>
<head>

{% extends 'Home/base.html' %}

<body>
{% block content %}
	<div id="posts" class="wf-section">
		<div id="Latest-post" class="container text-center">
			<div class="section-heading">
				<h2 class="section-title mt-5 " style="font-size: 26px;
				font-weight: 400;">THÔNG TIN LIÊN HỆ TRONG TRƯỜNG HỢP KHẨN CẤP</h2>
				<div class="med-divider"></div>
			</div>
			<br>
			<ul class="blog-title list-unstyled" style="color: black; padding-bottom: 57px;">
				<li>Đường dây nóng TC PCTT: 024.37333.3664 - 024.3734.9821</li>
				<li>Facebook: https://www.facebook.com/phongchongthientaivn</li>
				<li>Vụ Quản lý thiên tai cộng đồng: 024.3733.5804</li>
				<li>Đề tài cấp nhà nước ĐTĐL 78/21: 039.9750.875</li>
				<li>Email: canhbaothientaicongdong@gmail.com</li>
			</ul>
		</div>
	</div>
	

</section>

	<div class="from form-group text-center container">
		<div class="section-heading">
			<h2 class="section-title" style="font-size: 24px;
			font-weight: 400;">Liên hệ với chúng tôi</h2>
			<div class="med-divider"></div>
		</div>
		<form action="{% url 'Contact:getContact'%}" method="post" id="form1">
			{% csrf_token%}
			{{cf.as_p}}
			<input type ="Submit">	
		</form>	
	</div>
	<div class="from form-group text-center container">
		<div class="section-heading">
			<h2 class="section-title" style="font-size: 24px;
			font-weight: 400;">Đăng nhập/Đăng ký</h2>
			<div class="med-divider"></div>
		</div>
		<form action="{% url 'Contact:getContact'%}" method="post" id="form1">
			<a href="https://quantrac.maiatech.com.vn/Login" class="btn btn-primary btn-lg active" role="button" aria-pressed="true">Đăng nhập</a>
			<a href="https://quantrac.maiatech.com.vn/Register" class="btn btn-success btn-lg active" role="button" aria-pressed="true">Đăng ký</a>
		</form>	
	</div>
	

	{% comment %} <div class="from form-group text-center container">
		<div class="section-heading">
			<h2 class="section-title">Đăng nhập</h2>
			<div class="med-divider"></div>
		</div>
		<form method="POST" novalidate>
			{% csrf_token %}
			<h2>Login</h2>
			{{form.as_p}}
			<input type="submit" value="Login" />
		  </form>	
	</div>
	 {% endcomment %}

	 {% comment %} <div id="posts" class="wf-section">
		<div id="Latest-post" class="w-container">
			<div class="section-heading">
				<h2 class="section-title">ĐĂNG NHẬP</h2>
				<div class="med-divider"></div>
			</div>
			<br>
			<form action="{% url 'Contact:Contact'%}" method="post" style="text-align: center; display: block; padding-bottom: 57px;">
				{% csrf_token %}
				{{LF.as_p}}
				<input type="Submit">
			</form>	
		</div>
	</div>

	<div class="main-section bottom-padding w-container">
		<div class="section-heading">
			<h2 class="section-title">ĐĂNG KÍ THÀNH VIÊN</h2>
			<div class="med-divider"></div>
		</div>
		<form action="{% url 'Contact:Contact'%}" method="post" style="text-align: center; display: block;">
			{% csrf_token %}
			{{LF.as_p}}
			<input type="Submit">
		</form>	
	</div> {% endcomment %}

{% endblock %} 
</body>
</html>